# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
    push:
        branches:
            - master
            - Auto-FOX-0.8
    pull_request:

jobs:
    build:
        name: ${{ matrix.os }} (py ${{ matrix.version }}${{ matrix.special }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                version: ['3.7', '3.8', '3.9', '3.10']
                special: ['']
                include:
                    -   os: ubuntu-latest
                        special: '; conda'
                        version: '3.7'
                    -   os: ubuntu-latest
                        special: '; conda'
                        version: '3.8'
                    -   os: ubuntu-latest
                        special: '; conda'
                        version: '3.9'
                    -   os: ubuntu-latest
                        special: '; pre-release'
                        version: '3.9'
                    -   os: ubuntu-latest
                        special: '; minimum version'
                        version: '3.7'
        env:
            CP2K_DATA_DIR: /usr/share/cp2k/data

        steps:
            -   name: Cancel Previous Runs
                uses: styfle/cancel-workflow-action@0.9.1
                with:
                    access_token: ${{ github.token }}

            -   uses: actions/checkout@v2

            -   name: Set up Conda
                if: matrix.special == '; conda'
                uses: s-weigand/setup-conda@v1
                with:
                    update-conda: true
                    conda-channels: anaconda, conda-forge

            -   name: Set up Python
                if: matrix.special != '; conda'
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.version }}

            -   name: Install CP2K
                if: matrix.os == 'ubuntu-latest'
                run: sudo apt install cp2k

            -   name: Info CP2K
                if: matrix.os == 'ubuntu-latest'
                run: cp2k.popt --version

            -   name: Install dependencies
                shell: bash
                env:
                    SPECIAL: ${{ matrix.special }}
                    VERSION: ${{ matrix.version }}
                run: |
                    if [[ $SPECIAL == '; conda' ]]; then
                        conda create -n test -c conda-forge python=$VERSION rdkit
                        source $CONDA/bin/activate test
                        pip install -e .[test]
                    elif [[ $SPECIAL == '; pre-release' ]]; then
                        pip install --pre -e .[test_no_optional] --upgrade --force-reinstall
                        pip install git+https://github.com/SCM-NV/PLAMS@master --upgrade
                    elif [[ $SPECIAL == '; minimum version' ]]; then
                        pip install Nano-Utils==1.2.1 schema==0.7.1 AssertionLib==2.2 noodles==0.3.3 pyyaml==5.1 numpy==1.17 h5py==2.10 pandas==0.24 scipy==1.2.0
                        pip install -e .[test_no_optional]
                    else
                        pip install -e .[test_no_optional]
                    fi
                    pip install auto-FOX-data@git+https://github.com/nlesc-nano/auto-FOX-data@1.1.8

            -   name: Info Python
                shell: bash
                env:
                    SPECIAL: ${{ matrix.special }}
                run: |
                    if [[ $SPECIAL == '; conda' ]]; then
                        source $CONDA/bin/activate test
                        conda info
                    else
                        which python
                        python --version
                    fi

            -   name: Info installed packages
                shell: bash
                env:
                    SPECIAL: ${{ matrix.special }}
                run: |
                    if [[ $SPECIAL == '; conda' ]]; then
                        conda list -n test
                    else
                        pip list
                    fi

            -   name: Run tests
                shell: bash
                env:
                    SPECIAL: ${{ matrix.special }}
                run: |
                    if [[ $SPECIAL == '; conda' ]]; then
                        source $CONDA/bin/activate test
                    fi
                    pytest -m "not slow"

            -   name: Run codecov
                uses: codecov/codecov-action@v2
                with:
                    file: ./coverage.xml
                    name: codecov-umbrella

    Linting:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Python 3.9 on ubuntu-latest
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Install linters
                run: pip install flake8 pydocstyle

            -   name: Python info
                run: |
                    which python
                    python --version

            -   name: Installed packages
                run: pip list

            -   name: Run flake8
                run: flake8 FOX tests

            -   name: Run pydocstyle
                run: pydocstyle FOX
