# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
    push:
        branches:
            - master
            - Auto-FOX-0.8
    pull_request:

jobs:
    build:
        name: ${{ matrix.os }} (py ${{ matrix.version }}${{ matrix.special }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                version: [3.7, 3.8]
                special: ['']
                include:
                    - os: ubuntu-latest
                      special: '; pre-release'
                      version: 3.8
                    - os: ubuntu-latest
                      special: '; minimum version'
                      version: 3.7

        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.6.0
              with:
                access_token: ${{ github.token }}

            - uses: actions/checkout@v2

            - name: Set up Conda with Python ${{ matrix.version }} on ${{ matrix.os }}
              uses: s-weigand/setup-conda@v1
              with:
                update-conda: true
                python-version: ${{ matrix.version }}
                conda-channels: anaconda

            - name: Install conda-based dependencies
              if: matrix.special != '; minimum version'
              run: conda install -c conda-forge rdkit

            - name: Install conda-based dependencies (minimum version)
              if: matrix.special == '; minimum version'
              run: conda install -c conda-forge pyyaml=5.1 rdkit=2018.09 numpy=1.15 h5py=2.10 pandas=0.23 scipy=1.2.0 matplotlib

            - name: Install dependencies
              if: matrix.special == ''
              run: pip install .[test]
              env:
                CONDA_PREFIX: /usr/share/miniconda

            - name: Install dependencies (minimum version)
              if: matrix.special == '; minimum version'
              run: |
                pip install Nano-Utils==1.2.1 schema==0.7.1 AssertionLib==2.2 noodles==0.3.3
                pip install .[test]
              env:
                CONDA_PREFIX: /usr/share/miniconda

            - name: Install dependencies (pre-release)
              if: matrix.special == '; pre-release'
              run: pip install --pre .[test] --upgrade --force-reinstall
              env:
                CONDA_PREFIX: /usr/share/miniconda

            - name: Info Conda
              run: conda info

            - name: Info installed packages
              run: conda list

            - name: Run tests
              run: pytest -m "not slow" --flake8
              env:
                CONDA_PREFIX: /usr/share/miniconda

            - name: Run codecov
              uses: codecov/codecov-action@v1
              with:
                file: ./coverage.xml
                name: codecov-umbrella
